org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot
# Disable permission_handler storage permissions
permission_handler_camera=false
permission_handler_contacts=false
permission_handler_microphone=false
permission_handler_speech=false
permission_handler_photos=false
permission_handler_photosAddOnly=false
permission_handler_mediaLibrary=false
permission_handler_storage=false
permission_handler_manageExternalStorage=false
