// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpyqxGUn8tlHqGGPJu0-UdIRA2q9cTyI',
    appId: '1:1022247289156:android:e51d8a215e9d0071301711',
    messagingSenderId: '1022247289156',
    projectId: 'flutterustad',
    storageBucket: 'flutterustad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArwmZckMTDK3OQZ_vczrQX_28l1_1VzPE',
    appId: '1:1022247289156:ios:9332c5c73aeefc3e301711',
    messagingSenderId: '1022247289156',
    projectId: 'flutterustad',
    storageBucket: 'flutterustad.firebasestorage.app',
    androidClientId: '1022247289156-clnm5bhbp7ck9a2hu2ods7fr0dj410sh.apps.googleusercontent.com',
    iosClientId: '1022247289156-pdcks60lshoun3ds71cjpgbl7jatsr14.apps.googleusercontent.com',
    iosBundleId: 'com.dm.ustaad',
  );
}
