// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKoWaaLF0_5oelnY16EwS0mvDIQ1pm4s4',
    appId: '1:707536311548:android:5cd026fa4827d9bdcdb379',
    messagingSenderId: '707536311548',
    projectId: 'ustaad-77b25',
    storageBucket: 'ustaad-77b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO0GJiqh169UiuL4ybpf5h0w9NBNI5ol8',
    appId: '1:707536311548:ios:1a69389bf9b56fe4cdb379',
    messagingSenderId: '707536311548',
    projectId: 'ustaad-77b25',
    storageBucket: 'ustaad-77b25.firebasestorage.app',
    iosBundleId: 'com.example.ustaad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE06MhNfwmleJ8VgfY9i27QIHBwoitTRY',
    appId: '1:349544989753:web:placeholder',
    messagingSenderId: '349544989753',
    projectId: 'ustaad-5011f',
    authDomain: 'ustaad-5011f.firebaseapp.com',
    storageBucket: 'ustaad-5011f.firebasestorage.app',
  );
}